### PR TITLE
Add recent popular books to front page

### PR DESCRIPTION
**Pull request by samwilson**
Add a list of books popular in the last 3 months to the left side
of the main page. Also add a breadcrub link back to the main page
from the stats page.

This patch indents a bunch of lines; it's easier to see the changes if you use Github's "ignore whitespace changes" option.

### CODE REVIEW

**Comment by samwilson** [comment]
Thanks @tpt!

**Comment by zdzis** [comment]
@samwilson @Tpt, maybe it would be better (for _marketing_ reasons) in the list of popular books to give a link to the page in Wikisource instead of the direct download link?
What do you think?
Z.

**Comment by Tpt** [comment]
@zdzis Indeed, having both a link to Wikisource and a download links seems relevant to me.

**Comment by samwilson** [comment]
Good idea! I'll update it.

**Comment by samwilson** [comment]
See #203.

**Pull request merged**
